Apps/home/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "home_app"

urlpatterns = [
    path('',views.Inicio.as_view(),name="inicio"),
    path('registro',views.UserCreateView.as_view(),name="registrousuario"),
    path('login',views.Login.as_view(),name="loginusuario"),
    path('logout',views.Logout.as_view(),name="logoutusuario"),
    path('cambiarpassword',views.CambiarPassword.as_view(),name="cambiarpassword"),
    path('detalleusuario/<slug>/',views.UserDetailView.as_view(),name="detalleusuario"),
    path('updateusuario/',views.UsuarioUpdateView.as_view(),name="updateusuario"),
    path('eliminarusuario',views.UserDeleteView.as_view(),name="eliminarcuenta"),
    path('shoppingrecord',views.UserShoppingRecordView.as_view(),name="historialcompras"),
]

Apps/producto/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "productos_app"

urlpatterns = [
   path('productos',views.VistaProductos.as_view(),name="productos"),
   path('detalleproducto/<slug>/',views.DetalleProducto.as_view(),name="detalle"),
   path('agregarfavorito/<producto>/',views.FavoritoCreateView.as_view(),name="addfavorito"),
   path('carrito',views.VistaCarrito.as_view(),name="carrito"),
   path('borrardelcarrito/<producto>',views.BorrarDelCarrito.as_view(),name="borrardelcarrito"),
]

Apps/publicaciones/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "posts_app"

urlpatterns = [
    path('publicaciones',views.VistaPublicaciones.as_view(),name="publicaciones"),
    path('publicacion/<slug>',views.PublicacionView.as_view(),name="detallepost"),
    path('nuevapublicacion',views.NewPostView.as_view(),name="newpost"),
    path('editarpublicacion/<slug>',views.PostUpdateView.as_view(),name="editpost"),
    path('borrarfoto/<pk>',views.FotoDeleteView.as_view(),name="borrarfoto"),
]

rotar/urls.py
from django.contrib import admin
from django.urls import path, re_path,include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap

from Apps.home.sitemap import ProductosSitemap, Sitemap


sitemaps = {
    'site': Sitemap(['home_app:inicio']),
    'productos': ProductosSitemap
}

urlpatterns_sitemap = [
    path('sitemap.xml', sitemap,{'sitemaps':sitemaps},
    name='django.contrib.sitemaps.views,sitemap')

]

urlpatterns_main = [
    path('admin/', admin.site.urls),
    re_path('',include('Apps.home.urls')),
    re_path('',include('Apps.publicaciones.urls')),
    re_path('',include('Apps.producto.urls')),

    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns_main + urlpatterns_sitemap

rotar/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" class="min-vh-100">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'img/logo.ico' %}">
    <link rel="stylesheet" href="{%static '/css/estilos.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <script src="{% static 'fontawesome_free/js/all.min.js' %}"></script>

    <title> Rotar {% block title %}{% endblock title %} | Ecommerce</title>
</head>

<body>
    {% include 'header.html' %}
    {% block content %}{% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
        crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/17791cc8dc.js" crossorigin="anonymous"></script>
    <script
        src="https://code.jquery.com/jquery-3.6.0.js"
        integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
        crossorigin="anonymous"></script>
    <script src="{% static 'js/app.js' %}"></script>
    <script>
            $('#add_more').click(function() {
                cloneMore('div.table:last', 'fotos');
            });
        </script>
    {% include 'whatsapp.html' %}
    {% include 'footer.html' %}
</body>

</html>

rotar/templates/cajaprodhtal.html
{% load humanize %}

<div class="col-12 border border-info rounded p-1 mb-2 resaltar">

    <div class="row ">

        <div class="col-12 col-md-6 d-flex justify-content-center">
            
            <a href="{% url 'productos_app:detalle' p.slug %}"><img src="{{p.imagen.url}}" class="d-block rounded mw-100" style="height: 200px;" /></a>
        </div>

        <div class="col-12 col-md-6 ps-md-0 mx-1 mx-md-0">
            <div class="row" style="min-height: 50px;">
                <a href="{% url 'productos_app:detalle' p.slug %}" class="text-decoration-none align-self-center fs-6  resaltar-letra fw-bold">{{p.nombre|truncatechars:48}}</a>
            </div>
            <div class="row">

                <small class="text-secondary"> Publicado el {{p.created_at|date:"D d M Y"}}</small>
            </div>

            <div class="row">
                    <div class="fs-5">
                        Precio: <strong class="text-danger"> $ {{p.precio|intcomma}}</strong>
                    </div>
            </div>
            <div class="row align-items-center">

                <div class="col-6 col-md-6">
                    <i class="far fa-eye"></i> {{p.visitas}} &nbsp;
                </div>
                <div class="col-6 col-md-6 text-end">
                    {% if p.id  in favoritos%}
    
                    <form action="{% url 'productos_app:addfavorito' p.id %}" method="post"> {% csrf_token %}
    
                        <button type="submit" class="btn">
                            <i class="fas fa-star"></i>
                        </button>
    
                    </form>
                    {% else %}
                    
                    <form action="{% url 'productos_app:addfavorito' p.id %}" method="post"> {% csrf_token %}
    
                       <button type="submit" class="btn">
                            <i class="far fa-star"></i>
                        </button> 
    
                    </form>
                    {% endif %} 
    
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    Marca: {{p.marca}} <br>
                    <span> Categoria: {{p.categoria.nombre}}</span>
                </div>
                
                
    
            </div>

        </div>


    </div>

</div>

rotar/templates/cajaproducto.html
{% load humanize %}

<div class="col-12 border border-light rounded p-1 mb-2 resaltar">

    <div class="row align-self-center text-center" style="min-height: 60px;">
        <a href="{% url 'productos_app:detalle' p.slug %}" class="text-decoration-none align-self-center fs-5 text-center resaltar-letra fw-light">{{p.nombre|truncatechars:60}}</a>

    </div>
    <div class="row d-flex align-items-center mt-2">
        <div class="d-flex justify-content-center">

            <a href="{% url 'productos_app:detalle' p.slug %}"><img src="{{p.imagen.url}}" class="d-block rounded mw-100" style="height: 200px;" /></a>
        </div>
    </div>

    <div class="col-md-10 text-secondary"><small> Publicado el {{p.created_at|date:"D d M Y"}}</small>

    </div>

    <div class="col-12">
        <div class="row">


            <div class="col-8">
                Precio: <strong class="text-danger"> $ {{p.precio|intcomma}}</strong>

            </div>
            <div class="col-4 text-end">
                <i class="far fa-eye"></i> {{p.visitas}} &nbsp;

            </div>
        </div>
    </div>
    <div class="col-12">
        <div class="row">
            <div class="col-8">
                Marca: {{p.marca}} <br>
                <span> Categoria: {{p.categoria.nombre}}</span>
            </div>
            
            <div class="col-4 text-end">
                {% if p.id  in favoritos%}

                <form action="{% url 'productos_app:addfavorito' p.id %}" method="post"> {% csrf_token %}

                    <p><button type="submit" class="btn">
                        <i class="fas fa-star"></i>
                    </button> </p>

                </form>
                {% else %}
                
                <form action="{% url 'productos_app:addfavorito' p.id %}" method="post"> {% csrf_token %}

                    <p><button type="submit" class="btn">
                        <i class="far fa-star"></i>
                    </button> </p>

                </form>
                {% endif %} 

            </div>

        </div>
    </div>
</div>

rotar/templates/footer.html
<br>
<footer class="bg-dark">
    <div class="container text-white">

        <div class="row py-1 align-items-center">
            <div class="col-12 col-md-4 text-center">
                <div class="fs-5">
                    Contactanos
                </div>
                <div class="fs-6">
                    <small>
                    Carrera 16 # 185-17 <br>
                    3013497748 - 3017101052 - 3153162833  <br>
                    ventas@rotarengineering.com.co  <br>
                    Bogotá, Colombia
                    </small> 
                        
                </div>
            </div>
            <div class="col-12 col-md-4 d-flex flex-column align-items-center">
                <br class="d-md-none">
                    <div class="row">
                        <div class="fs-6">
                            Politicas de uso
                        </div>
                    </div>
                    <div class="row">
                        <div class="fs-6">
                            Información legal
                        </div>
                    </div>
                    <div class="row">
                        <div class="fs-6">
                            Filosofía organizacional
    
                        </div>
                    </div>
            </div>

            <div class="col-12 col-md-4 ">
                <br class="d-md-none">
                <div class="row text-center">
                    <div class="fs-5">Siguenos en:</div>
                </div>
                <div class="row text-center mx-2 p-2 justify-content-center">
                    <div class="col-2">
                        <div class="fs-4"><i class="fab fa-facebook-square"></i> </div>
                    </div>
                    <div class="col-2">
                        <div class="fs-4"><i class="fab fa-twitter-square"></i> </div>
                        
                    </div>
                    <div class="col-2">
                        <div class="fs-4"><i class="fab fa-linkedin"></i> </div>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

rotar/templates/header.html
{% load static %}

<div class="sticky-top">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      
      <a class="navbar-brand p-0 m-0" href="{% url 'home_app:inicio' %}"><img src="{% static 'img/logoblanco.png' %}" style="width: 60px;"></a>
      
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            {% if request.path == '/' %}
            <a class="nav-link active" aria-current="page" href="{% url 'home_app:inicio' %}">Inicio</a>
            {% else %}
            <a class="nav-link" href="{% url 'home_app:inicio' %}">Inicio</a>
            {% endif %}
          </li>
          <li class="nav-item">
            {% if request.path == '/productos' %}
            <a class="nav-link active" aria-current="page" href="{% url 'productos_app:productos' %}">Productos</a>
            {% else %}
            <a class="nav-link" href="{% url 'productos_app:productos' %}">Productos</a>
            
            {% endif %}
          </li>
          <li class="nav-item">
            {% if request.path == '/publicaciones' %}
            <a class="nav-link active" aria-current="page" href="{% url 'posts_app:publicaciones' %} ">Publicaciones</a>
            {% else %}
            <a class="nav-link" href="{% url 'posts_app:publicaciones' %} ">Publicaciones</a>

            {% endif %}
          </li>
        </ul>
      </div>
      <span class="navbar-text">
        {% if user.username %}

        <a class="text-decoration-none text-white fw-lighter" href="{% url 'home_app:detalleusuario' user.slug %} "> <i class="fas fa-user-astronaut"> </i> Mi perfil</a> &nbsp;
        <a class="text-decoration-none text-white fw-lighter" href="{% url 'home_app:logoutusuario' %} "> <i class="fas fa-sign-out-alt"> </i> Salir </a> &nbsp;

        {%else%}

        <a class="text-decoration-none text-white fw-lighter" href="{% url 'home_app:registrousuario' %} "><i class="fas fa-tasks"> </i> Registro</a>
        <a class="text-decoration-none text-white fw-lighter" href="{% url 'home_app:loginusuario' %} "><i class="fas fa-user-astronaut"> </i> Ingreso </a>

        {% endif %}

        <a type="submit" class="btn m-0 position-relative p-0" href="{% url 'productos_app:carrito' %}">
          <i class="fas fa-shopping-cart fa-lg"></i>
          <span style="font-size: 0.6rem;" class="badge bg-danger position-absolute translate-middle">
            {{cantidad_carrito}}
          </span>
        </a>

      </span>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
        aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        
      </button>
    </div>
  </nav>
  <nav class="navbar navbar-expand-lg navbar-secondary bg-secondary d-flex justify-content-evenly text-white p-1">
    
    {% for c in categorias_nombres %}
      <a class="text-decoration-none text-white" href="{% url 'productos_app:productos'  %}?categoria={{c.0}}"> {{c.0}} &nbsp;</a>
    {% endfor %}
      


  </nav>
  
</div>

rotar/templates/paginacion.html
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center" style="padding: 10px;">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {% endif %}
    
    {% for pagina in page_obj.paginator.page_range %}

    {% ifequal pagina page_obj.number %}
    <li class="page-item active" aria-current="page"><a class="page-link bg-dark border-dark" href="#">{{pagina}}</a></li>

    {%else%}
    <li class="page-item"><a class="page-link" href="?page={{pagina}}">{{pagina}}</a></li>
    {% endifequal %}

    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>

    {% endif %}
  </ul>
</nav>

rotar/templates/whatsapp.html
{% load static %}
<div class="fixed-bottom text-end px-4 pb-1">
    <a href="https://wa.me/573013497748?text=Me%20interesa%20los%20productos%20que%20están%20vendiendo" target="_blank"><img src="{% static 'img/whatsapp.png' %}" alt="" style="max-height: 70px;"> </a>
</div>