Apps/producto/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "productos_app"

urlpatterns = [
   path('productos',views.VistaProductos.as_view(),name="productos"),
   path('detalleproducto/<slug>/',views.DetalleProducto.as_view(),name="detalle"),
   path('agregarfavorito/<producto>/',views.FavoritoCreateView.as_view(),name="addfavorito"),
   path('carrito',views.VistaCarrito.as_view(),name="carrito"),
   path('borrardelcarrito/<producto>',views.BorrarDelCarrito.as_view(),name="borrardelcarrito"),
]

rotar/urls.py
from django.contrib import admin
from django.urls import path, re_path,include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap

from Apps.home.sitemap import ProductosSitemap, Sitemap


sitemaps = {
    'site': Sitemap(['home_app:inicio']),
    'productos': ProductosSitemap
}

urlpatterns_sitemap = [
    path('sitemap.xml', sitemap,{'sitemaps':sitemaps},
    name='django.contrib.sitemaps.views,sitemap')

]

urlpatterns_main = [
    path('admin/', admin.site.urls),
    re_path('',include('Apps.home.urls')),
    re_path('',include('Apps.publicaciones.urls')),
    re_path('',include('Apps.producto.urls')),

    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns_main + urlpatterns_sitemap

Apps/producto/models.py
from datetime import datetime, timedelta

from django.db import models
from ckeditor.fields import RichTextField

from django.conf import settings

from django.contrib.auth import get_user_model
from django.template.defaultfilters import slugify
from django.urls import reverse_lazy
User = get_user_model()

from Apps.producto.managers import FotosProductosManager, ProductosManager

# Create your models here.
class CategoriaProducto(models.Model):
    nombre = models.CharField(verbose_name="Categoria", max_length=100)
    descripcion = models.CharField(verbose_name="Descripcion", max_length=250)
    
    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"
    
    def __str__(self):
        return self.nombre
    
class Color(models.Model):
    color = models.CharField(max_length=50)
    codigo = models.CharField(max_length=7)
    
    class Meta:
        verbose_name = "Color"
        verbose_name_plural = "Colores"
    
    def __str__(self):
        return self.color

class Talla(models.Model):
    talla = models.CharField(max_length=50)
    
    class Meta:
        verbose_name = "Talla"
        verbose_name_plural = "Tallas"
    
    def __str__(self):
        return self.talla
    
    
class Producto(models.Model):
    
    nombre = models.CharField(max_length=150,verbose_name="Nombre")
    marca = models.CharField(verbose_name="Marca", max_length=250, default=None)
    cantidad = models.IntegerField()
    precio = models.IntegerField()
    categoria = models.ForeignKey(CategoriaProducto, on_delete=models.CASCADE, verbose_name="Categorias")
    imagen = models.ImageField(upload_to="media", height_field=None, width_field=None, max_length=None,blank=True)
    descripcion = RichTextField(verbose_name="Descripcion",blank=True)
    color = models.ManyToManyField(Color,blank=True, related_name="coloresproducto")
    talla = models.ManyToManyField(Talla,blank=True, related_name="tallasproducto")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="Usuario", on_delete=models.CASCADE, editable=False)
    publico = models.BooleanField(default=False)
    visitas = models.IntegerField(default=0, editable=False)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Creado el")
    updated_at= models.DateTimeField(auto_now=True, verbose_name="Actualizado el")
    slug = models.SlugField(default="",editable=False,max_length=150)
    
    objects = ProductosManager()
    
    class Meta:
        verbose_name= "Producto"
        verbose_name_plural = "Productos"
    
    def __str__(self):
        return self.nombre

    def save(self,*args, **kwargs):
        
        if not self.slug:
            now = datetime.now()
            total_time = timedelta(
                hours=now.hour,
                minutes=now.minute,
                seconds=now.second
            )

            seconds = int(total_time.total_seconds())
            slug_unique = '%s-%s-%s' % (self.nombre,self.marca, str(seconds))
            self.slug = slugify(slug_unique)

        super(Producto,self).save(*args, **kwargs)
    
    def get_absolute_url(self):
    
        return reverse_lazy(
            'productos_app:detalle',
            kwargs = {
                'slug': self.slug
            }
        
    )

class FotoProducto(models.Model):
    MAX_FOTOS = 7
    
    producto = models.ForeignKey(Producto, verbose_name=("Producto"), on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="media", height_field=None, width_field=None, max_length=None,blank=False)
    
    objects = FotosProductosManager()
    
    class Meta:
        verbose_name= "Foto"
        verbose_name_plural = "Fotos"
        
    def __str__(self):
        return str(self.imagen) 


class Favorito(models.Model):
    
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Creado el")
    
    class Meta:
        unique_together = ('producto','user')
        verbose_name = 'Favorito'
        verbose_name_plural = 'Favoritos'

    def __str__(self):
        return self.producto.nombre


class Venta(models.Model):
    
    
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,blank=True, null=True)
    fecha_venta = models.DateTimeField('Fecha de Venta',)
    valor_total = models.IntegerField()
    nombre = models.CharField(max_length=150,blank=False)
    apellido = models.CharField(max_length=150,blank=False)
    email = models.EmailField(max_length=254,blank=False)
    direccion = models.CharField(max_length=350,blank=False)
    ciudad = models.CharField(max_length=50,blank=False)
    departamento = models.CharField(max_length=50,blank=False)
    celular = models.CharField(max_length=15)
    forma_pago = models.CharField(max_length=25)
    
    class Meta:
        verbose_name = 'Venta'
        verbose_name_plural = 'Ventas'

    def __str__(self):
        fecha = str(self.fecha_venta.strftime('%d-%m-%y %H:%M'))
        return f'ID={self.id} - {fecha} - {self.nombre} {self.apellido} - Total $ {self.valor_total}'

class DetalleVenta(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    venta = models.ForeignKey(Venta, on_delete=models.CASCADE)
    info_extra = models.CharField(max_length=150, blank=True,default=" ")
    cantidad = models.IntegerField()
    subtotal = models.IntegerField()
    
    
    class Meta:
        verbose_name = 'Producto Vendido'
        verbose_name_plural = 'Productos vendidos'

    def __str__(self):
        return f"{self.producto}"
    

Apps/producto/views.py
from django.shortcuts import render
from django.utils import timezone
# Create your views here.
from django.views.generic import ListView, FormView, TemplateView, View, CreateView
from Apps.producto.models import CategoriaProducto, Color, DetalleVenta, Favorito, FotoProducto, Producto, Venta
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin 


from Apps.producto.forms import CarritoForm, VentaForm
from django.db.models import Avg, Count, FloatField, Max
from django.http import HttpResponseRedirect
import random
from django.contrib import messages
from django.core.paginator import Paginator


class VistaProductos(ListView):
    
    model = Producto
    template_name= "productos/lista.html"
    paginate_by = 12
    context_object_name= "productos"
    
    def get_context_data(self, **kwargs):
        context = super(VistaProductos,self).get_context_data(**kwargs)
        context["categoria"] = self.request.GET.get("categoria",'')
        context["kword"] = self.request.GET.get("kword",'')
        context['orden'] = self.request.GET.get("orden",'')
        
        #context["precios"] = context["productos"].aggregate(Avg('precio'),Max('precio'))
        context["categorias"] = CategoriaProducto.objects.all().annotate(cant_prod=Count('producto'))
        # context["favoritos"] = Favorito.objects.filter(user__id = self.request.user.id).values_list('producto__id',flat=True)
        context["todos"] = Producto.objects.all().aggregate(total=Count('id'))
    #     context["precio_diff"] = Producto.objects.aggregate(price_diff=Max('precio', output_field=FloatField()) - Avg('precio'))
        return context
    
    def get_queryset(self):
        kword = self.request.GET.get("kword",'')
        categoria = self.request.GET.get("categoria",'')
        orden = self.request.GET.get("orden",'')
        
        #TODO: toca arreglar el buscador y todo eso para los filtros, por ahora que de un solo boton se hagan los cambios
        lista = Producto.objects.buscar_pub(kword,categoria,orden)
        return lista

class DetalleProducto(FormView):
    
    form_class = CarritoForm
    template_name= "productos/detalle.html"
    success_url = reverse_lazy('productos_app:productos')
    
    def get_context_data(self, **kwargs):
        context = super(DetalleProducto,self).get_context_data(**kwargs)
        context['producto'] =  Producto.objects.get(slug=self.kwargs['slug'])
        context['producto'].visitas +=1
        context['producto'].save(update_fields=['visitas'])
        context['colores'] = Color.objects.filter(coloresproducto__id=context['producto'].id)
        context['galeria'] = FotoProducto.objects.fotos_producto(self.kwargs['slug'])
        x = list(Producto.objects.filter(categoria=context['producto'].categoria).order_by('created_at').exclude(id=context['producto'].id)[:10])
        try:
            producto_recomendado = random.sample(x,k=1)
        except:
            producto_recomendado = []
        context['productos']= producto_recomendado
        
        #muestra de populares
        muestra_populares = list(Producto.objects.all().order_by('-visitas')[:10])
        populares = random.sample(muestra_populares,k=2)
        context["populares"] = populares
        
        return context
    
    def get_form_kwargs(self):
        kwargs = super(DetalleProducto, self).get_form_kwargs()

        # get users, note: you can access request using: self.request
        producto = Producto.objects.get(slug=self.kwargs['slug'])
        kwargs['id'] = producto.id
        kwargs['slug'] = self.kwargs['slug']
        try:
            kwargs['cart'] = self.request.session['cart']
        except:
            kwargs['cart'] = {}
        return kwargs

    def form_valid(self,form):
        extra_info = {
            'color': str(form.cleaned_data['color']),
            'talla': str(form.cleaned_data['talla'])
        }
        #extra_info=f"Color: {form.cleaned_data['color']}, Talla: {form.cleaned_data['talla']}, Tamaño: {form.cleaned_data['size']}"

        cart = self.request.session.get('cart', {})
        prod = f"{self.kwargs['slug']}{form.cleaned_data['color']}{form.cleaned_data['talla']}"

        cart[prod] = [self.kwargs['slug'],form.cleaned_data['cantidad'],extra_info]
        
        self.request.session['cart'] = cart
        messages.success(self.request, "Producto agregado al carrito con exito")
        return HttpResponseRedirect(self.request.META.get('HTTP_REFERER'))   

class VistaCarrito(CreateView):
    
    form_class= VentaForm
    template_name= "productos/carrito.html"
    
    def get_context_data(self, **kwargs):
        context = super(VistaCarrito,self).get_context_data(**kwargs)
        lista = []
        total = 0
        total1 = 0
        costo_envio = 9500
        try:
            if len(self.request.session['cart']) >=1:
                for x in self.request.session['cart']:
                    cantidad = self.request.session['cart'][x][1]
                    j = Producto.objects.get(slug=self.request.session['cart'][x][0])
                    extra_info = self.request.session['cart'][x][2]
                    identificador = x
                    subtotal = j.precio * cantidad
                    lista.append([j,cantidad,subtotal,extra_info,x])
                    total1 += subtotal
                
                p = Paginator(lista,5) 
                page_number = self.request.GET.get('page')
                page_obj = p.get_page(page_number)
                context["page_obj"] = page_obj
                # context["carrito"] = lista
                if total1 >250000:
                    context["descontado"] = costo_envio
                    costo_envio = 0
                total = total1 + costo_envio
                context["subtotal"] = total1
                context["costo_envio"] = costo_envio
                context["total"] = total
            else:
                raise Exception
            
        except:
            context["page_obj"] = lista
            # context["carrito"] = lista
            context["costo_envio"] = 0
            total = total1
            context["subtotal"] = total
            context["total"] = total
        
        tototal = self.request.session.get('total', {})
       # print(self.request.session['total'])
        tototal['total'] = total
        self.request.session['total'] = tototal
        
        #muestra de populares
        muestra_populares = list(Producto.objects.all().order_by('-visitas')[:10])
        populares = random.sample(muestra_populares,k=2)
        context["populares"] = populares
            
        return context
    
    def get_form_kwargs(self):
        kwargs = super(VistaCarrito, self).get_form_kwargs()
        try:
            kwargs['total'] = self.request.session['total']['total']
        except:
            kwargs['total'] = 0
        return kwargs

    def form_valid(self, form):

        if len(self.request.session["cart"])>0:
            
            venta = Venta.objects.create(
                fecha_venta = timezone.now(),
                valor_total = self.request.session['total']['total'],
                nombre = form.cleaned_data["nombre"],
                apellido = form.cleaned_data["apellido"],
                email = form.cleaned_data["email"],
                direccion = form.cleaned_data["direccion"],
                ciudad = form.cleaned_data["ciudad"],
                departamento = form.cleaned_data["departamento"],
                celular = form.cleaned_data["celular"],
                forma_pago = form.cleaned_data["forma_pago"],
            )
            
            if self.request.user.username:
                venta.user = self.request.user
                venta.save()
            
            lista = []
            for x in self.request.session['cart']:
                i = self.request.session['cart'][x][1]
                j = Producto.objects.get(slug=self.request.session['cart'][x][0])
                subtotal = j.precio *i
                extra_info = self.request.session['cart'][x][2]
                lista.append([j,i,subtotal,extra_info])
                    
            # for x,y in zip(productos,cantidades):
            #     subtotal = x.precio * y
            
            detalle_productos = []
            actualizar_productos = []
            for detalle in lista:
                detalle_venta = DetalleVenta(
                    producto = detalle[0],
                    venta = venta,
                    cantidad = detalle[1],
                    subtotal = detalle[2],
                    info_extra = f"Color: {detalle[3]['color']}, Talla: {detalle[3]['talla']}" 
                )
                detalle_productos.append(detalle_venta)
                
                producto = detalle[0]
                if producto in actualizar_productos:
                    i = actualizar_productos.index(producto)
                    print(actualizar_productos[i].cantidad)
                    actualizar_productos[i].cantidad = actualizar_productos[i].cantidad - detalle[1]
                else:   
                    producto.cantidad = producto.cantidad - detalle[1] 
                    actualizar_productos.append(producto)
            DetalleVenta.objects.bulk_create(detalle_productos)
            # actualizamos el stock
            Producto.objects.bulk_update(actualizar_productos, ['cantidad'])
            del self.request.session['cart']
            del self.request.session['total']
            
            messages.success(self.request, "Felicidades, la compra ha sido aprobada, en los proximos minutos te llegará un email de confirmación")
            
            return HttpResponseRedirect(
                    reverse('home_app:inicio'))
        else:
            return None
        
class BorrarDelCarrito(View):
    
    def post(self,request,*args,**kwargs):
        
        producto = self.kwargs["producto"]
        try:

rotar/templates/productos/detalle.html
{% extends 'base.html' %}
{%load static%}
{% load humanize %}
{% block title %}Detalle producto {{producto.nombre}} - {{producto.categoria}}{% endblock title %}


{% block content %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-success py-1" role="alert">
  {{message}}
</div>
{% endfor %}
{% endif %}

<div class="container">
    <br>
    <div class="row justify-content-center">
        <div class="col-md-8 py-2">
            <div class="row">
                <div class="col-md-7">
                    <div id="carouselExampleFade" class="carousel slide" data-bs-ride="carousel">
                        <div class="carousel-inner" >
                            {% if producto.imagen.url %}
                            <div class="carousel-item active " >
                                
                                <a role="button" data-bs-toggle="modal" data-bs-target="#exampleModal{{producto.id}}"><img src="{{producto.imagen.url}}" alt="" class="w-100 rounded pequenosize normalsize"></a>
                            </div>
                            
                                <div class="modal fade" id="exampleModal{{producto.id}}" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog modal-lg">
                                      <div class="modal-content">
                                        <div class="modal-header">
                                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            <img src="{{producto.imagen.url}}" alt="" class="w-100 rounded" >
                                        </div>
                                        <div class="modal-footer">
                                          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
        
                            {% else %}
                            <div class="carousel-item active">

                                <img src="{% static 'img/no-image.png' %}" class="d-block w-100 rounded">
                            </div>
                            {% endif %}
                            
                            {% for foto in galeria %}
                            
                                <div class="carousel-item">
                                    <a role="button" data-bs-toggle="modal" data-bs-target="#exampleModal{{foto.id}}"><img src="{{foto.imagen.url}}" alt="" class="w-100 rounded pequenosize normalsize" ></a>
                                </div>
                                <div class="modal fade" id="exampleModal{{foto.id}}" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog modal-lg">
                                      <div class="modal-content">
                                        <div class="modal-header">
                                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            <img src="{{foto.imagen.url}}" alt="" class="w-100 rounded" >
                                        </div>
                                        <div class="modal-footer">
                                          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
        
                            {% endfor %}
                        </div>
                        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade"
                            data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Previous</span>
                        </button>
                        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade"
                            data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Next</span>
                        </button>
                    </div>

                </div>
                <div class="col-md-5">
                    <div class="row align-items-center">

                        <div class="fs-4">{{producto.nombre}}</div>
                        <div class="fs-6 text-secondary fst-italic">Publicado el: {{producto.created_at|date:"D d M Y"}}
                        </div>
                        <div>Marca: {{producto.marca}}</div>
                        
                        <div class="col-9">
                            <div class="fs-5 mb-2">Precio: <span class="text-danger fs-2">$ {{producto.precio|intcomma}}</span>
                            </div>
                            <div class="fs-5">Categoria:
                                <span class="badge bg-primary fs-6">{{producto.categoria}}</span>
        
                            </div>

                        </div>
                        <div class="col-3 text-center">

                            {% if producto.id in favoritos%}
        
                                <form action="{% url 'productos_app:addfavorito' producto.id %}" method="post"> {% csrf_token %}
        
                                    <p><button type="submit" class="btn">
                                        <i class="fas fa-star fa-2x text-primary"></i>
                                    </button> </p>
        
                                </form>
                            {% else %}
                            
                                <form action="{% url 'productos_app:addfavorito' producto.id %}" method="post"> {% csrf_token %}
        
                                    <p><button type="submit" class="btn">
                                        <i class="far fa-star fa-2x text-primary"></i>
                                    </button> </p>
        
                                </form>
                            {% endif %} 
                        </div>

                        <div class="fs-5 fw-light fst-italic">Visitas: {{producto.visitas}}</div>

                        
                    </div>


                </div>
            </div>
            <br>
            <div class="row border border-info mx-1 rounded">
                <div class="col-md-12 letrapequena">
                    <h4 class="text-secondary fw-light">Descripción del producto</h4>
                    <p>{{producto.descripcion|safe}} </p>
                </div>
            </div>
            <br class="d-none d-md-block">
            <div class="row mx-1 d-none d-md-block">
                <br>
                <div class="row mb-3">
                    <h1> <i class="fas fa-meteor"></i> Productos populares</h1>
                </div>
                <div class="row mx-0 px-0">
                    {% for p in populares %}
                    <div class="col-md-6 px-1">
                        {% include 'cajaprodhtal.html' %}
                    </div>
                    {% endfor %}
                </div>
            </div>


        </div>
        <div class="col-12 col-md-3 ">
            <div class="row border rounded border-info justify-content-center mx-1">

                <div class="row pt-3 text-center mb-1">
                    <h4 class="text-danger">Agregar producto al carrito</h4>
                </div>
                <br>
                <div class="row">
                <form method="post"> {% csrf_token %}
                    <div class="row justify-content-center">
                        <div class="col-9">
                                {% if producto.color.all|length > 0 %}
                                <div class="col-12 border rounded p-2 align-self-center text-center mb-2">
            
                                    <h6>Selecciona un color</h6>
                                    {% for p in producto.color.all %}
                                    <div class="row ">
                                        <div class="col-3">
                                            <input class="form-check-input" name="color" id="id_color" type="radio"
                                                value="{{p.id}}">
            
                                        </div>
                                        <div class="col-6 rounded m-1" style="background-color:{{p.codigo}};">
                                            <label class="form-check-label" for="flexRadioDefault1"></label>
            
                                        </div>
                                    </div>
            
                                    {% endfor %}
            
                                </div>
                                {% endif %}
        
                                <div class="col-12 d-flex align-items-center  ">
                                    {% if producto.talla.all|length > 0 %}
                                    <div class="input-group">
                                        <label class="input-group-text">Talla:
                                        </label>{{form.talla}}
                                    </div>
                                    {% endif %}
            
                                </div>
                            </div>
    
                    </div>
                    <br>
                    <div class="row justify-content-center">
                        <div class="col-9 d-flex align-items-center">
                            <div class="input-group">
                                <label class="input-group-text">Cantidad:
                                </label>{{form.cantidad}}
                            </div>
    
                        </div>
                        
                    </div>
                    <br>
                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                            <div class="alert alert-info alert-dismissible fade show" role="alert">
                                {{ error|escape }}
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                              </div>
                            {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                        <div class="alert alert-info alert-dismissible fade show" role="alert">
                            {{ error|escape }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                          </div>
                        {% endfor %}
                    {% endif %}
                        
                    <div class="row justify-content-center mb-2">
                        <div class="col-md-10">
                            <div class="row">
    
                                <button type="submit" class="btn btn-dark"> Agregar al carrito</button>
                            </div>
                        </div>
    
                    </div>
                    
                    <div class="row justify-content-center mb-2">
                        <div class="col-md-10">
                            <div class="row">
                                <a class="btn btn-danger" href="{% url 'productos_app:carrito' %}"> Ir al carrito</a>
                            </div>
                        </div>
    
                    </div>
                    </form>
                </div>
            </div>
            <br>

            
            {% if productos %}
                
            <div class="row bg-dark rounded align-items-center mb-2 mx-1">
                <div class="col-3">
                    <div class="fs-2">
                        <img src="{% static 'img/logoblanco.png' %}" alt="" class="w-100 d-block">
                    </div>
                </div>
                <div class="col-9">
                    <div class="fs-2 text-center bg-dark rounded text-white my-1 lh-sm">Producto recomendado</div>
                </div>
            </div>
            <div class="row mx-1 mt-2">
                
                {% for p in productos  %}
                    {% include 'cajaproducto.html' %}

                {% endfor %}
            </div>
            {% endif %}
                
        </div> 

    </div>
        
</div>



{% endblock content %}