Apps/publicaciones/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "posts_app"

urlpatterns = [
    path('publicaciones',views.VistaPublicaciones.as_view(),name="publicaciones"),
    path('publicacion/<slug>',views.PublicacionView.as_view(),name="detallepost"),
    path('nuevapublicacion',views.NewPostView.as_view(),name="newpost"),
    path('editarpublicacion/<slug>',views.PostUpdateView.as_view(),name="editpost"),
    path('borrarfoto/<pk>',views.FotoDeleteView.as_view(),name="borrarfoto"),
]

rotar/urls.py
from django.contrib import admin
from django.urls import path, re_path,include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap

from Apps.home.sitemap import ProductosSitemap, Sitemap


sitemaps = {
    'site': Sitemap(['home_app:inicio']),
    'productos': ProductosSitemap
}

urlpatterns_sitemap = [
    path('sitemap.xml', sitemap,{'sitemaps':sitemaps},
    name='django.contrib.sitemaps.views,sitemap')

]

urlpatterns_main = [
    path('admin/', admin.site.urls),
    re_path('',include('Apps.home.urls')),
    re_path('',include('Apps.publicaciones.urls')),
    re_path('',include('Apps.producto.urls')),

    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns_main + urlpatterns_sitemap

Apps/publicaciones/models.py
from datetime import datetime, timedelta

from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()
from ckeditor.fields import RichTextField
from django.conf import settings

from .managers import FotosManager
from Apps.publicaciones.managers import ComentariosManager, PublicacionesManager, EtiquetasManager
from django.template.defaultfilters import slugify

# Create your models here.
class Etiqueta(models.Model):
    nombre = models.CharField(verbose_name="Etiqueta", max_length=100)
    descripcion = models.CharField(verbose_name="Descripcion", max_length=250)
    
    objects = EtiquetasManager()
    
    class Meta:
        verbose_name = "Etiqueta"
        verbose_name_plural = "Etiquetas"
    
    def __str__(self):
        return self.nombre
    
class Publicacion(models.Model):
    
    titulo = models.CharField(max_length=150,verbose_name="Titulo")
    resumen = models.CharField(verbose_name="Resumen", max_length=250)
    etiquetas = models.ManyToManyField(Etiqueta, verbose_name="Etiquetas", blank=True, related_name="tags_pubs")
    imagen = models.ImageField(upload_to="media", height_field=None, width_field=None, max_length=None,blank=True)
    video = models.FileField(verbose_name="Video", upload_to="media",blank=True)
    descripcion = RichTextField(verbose_name="Descripcion",blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="Usuario", on_delete=models.CASCADE, editable=False)
    publico = models.BooleanField(default=False)
    visitas = models.IntegerField(default=0, editable=False)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Creado el")
    updated_at= models.DateTimeField(auto_now=True, verbose_name="Actualizado el")
    slug = models.SlugField(default="",editable=False,max_length=150)
    
    
    objects = PublicacionesManager()
    class Meta:
        verbose_name= "Publicación"
        verbose_name_plural = "Publicaciones"
        ordering = ["titulo","-created_at"]
        # db_table = 'publicaciones'
    
    def __str__(self):
        return self.titulo
    
    def save(self,*args, **kwargs):
        
        if not self.slug:
            now = datetime.now()
            total_time = timedelta(
                hours=now.hour,
                minutes=now.minute,
                seconds=now.second
            )

            seconds = int(total_time.total_seconds())
            slug_unique = '%s-%s' % (self.titulo, str(seconds))
            self.slug = slugify(slug_unique)

        super(Publicacion,self).save(*args, **kwargs)

class Foto(models.Model):
    
    MAX_FOTOS = 5
    
    publicacion = models.ForeignKey(Publicacion, verbose_name=("Publicacion"), on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="media", height_field=None, width_field=None, max_length=None,blank=False)

    
    objects = FotosManager()
    
    class Meta:
        verbose_name= "Foto"
        verbose_name_plural = "Fotos"
        
    def __str__(self):
        return str(self.imagen) 

class Comentario(models.Model):
    
    Publicacion = models.ForeignKey(Publicacion, verbose_name=("Publicacion"), on_delete=models.CASCADE)
    mensaje = models.CharField(verbose_name="Mensaje", max_length=250)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="Usuario", on_delete=models.CASCADE, editable=False)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Creado el")
    updated_at= models.DateTimeField(auto_now=True, verbose_name="Actualizado el")
    
    objects = ComentariosManager()
    
    class Meta:
        verbose_name= "Comentario"
        verbose_name_plural = "Comentarios"
        
    def __str__(self):
        return "Comentario de: "+ str(self.user) + " en la publicacion: "+ str(self.Publicacion)
    
    
    

Apps/publicaciones/forms.py
from django import forms
from Apps.publicaciones.models import Foto, Publicacion
from django.forms.models import inlineformset_factory
from ckeditor.fields import RichTextFormField

class NewPostForm(forms.ModelForm):
    
    descripcion = RichTextFormField(config_name="refault")
    
    class Meta:
        model = Publicacion
        fields = ('titulo','resumen','etiquetas','descripcion','imagen','publico',)
        widgets = {
            'titulo': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'resumen': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'imagen': forms.FileInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'publico': forms.CheckboxInput(
                attrs={
                    'class': 'form-check-input',
                }
            ),
            'etiquetas': forms.SelectMultiple(
                attrs={
                    'class': 'form-select',
                    'size': 6
                }
            ),            
        }


PostFormSet = inlineformset_factory(
        Publicacion, 
        Foto, 
        fields=('imagen',),
        can_delete=False, 
        max_num=5,
        widgets= {
            'imagen': forms.FileInput(
                attrs={
                        'class': 'form-control'
                    }
                )
            }
    )
    

Apps/publicaciones/views.py
from datetime import datetime
import random

from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.db.models import Avg, Count
from django.contrib.auth import get_user_model
User = get_user_model()
from django.db.models.functions import Lower
from django.contrib.auth.mixins import LoginRequiredMixin 
from django.core.paginator import Paginator

from django.views.generic import ListView, DetailView, CreateView, TemplateView, FormView, UpdateView, View

from Apps.publicaciones.models import Comentario, Etiqueta, Foto, Publicacion
from Apps.publicaciones.forms import NewPostForm, PostFormSet
from Apps.producto.models import Favorito, Producto
from django.contrib import messages
from django.http import HttpResponseRedirect
# Create your views here.


class VistaPublicaciones(ListView):
    
    model = Publicacion
    template_name= "publicaciones/lista.html"
    paginate_by = 5
    context_object_name= "publicaciones"
    
    def get_context_data(self, **kwargs):
        context = super(VistaPublicaciones,self).get_context_data(**kwargs)
        context["etiquetas"] = Etiqueta.objects.all()
        context["etiqueta"] = self.request.GET.get("etiqueta",'')
        context["kword"] = self.request.GET.get("kword",'')
        context['orden'] = self.request.GET.get("orden",'')
        
        #Usando el values que funciona como el group by de SQL
        #context["comments"] = Comentario.objects.values('user').annotate(cuenta=Count('user'),nombre=Lower('user__username'))
        
        return context
    
    def get_queryset(self):
        kword = self.request.GET.get("kword",'')
        etiqueta = self.request.GET.get("etiqueta",'')
        orden = self.request.GET.get("orden",'')
        
        #TODO: toca arreglar el buscador y todo eso para los filtros, por ahora que de un solo boton se hagan los cambios
        lista = Publicacion.objects.buscar_pub(kword,etiqueta,orden).annotate(comments_count=Count('comentario', distinct=True),fotos_count=Count('foto', distinct=True))
        return lista

    


class PublicacionView(CreateView):
    model= Comentario
    fields = ('mensaje',)
    template_name= "publicaciones/detalle.html"
    
    
    #En este view se puede ver el detalle de la publicacion, las fotos, comentarios y se puede agregar un comentario
    
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        context['publicacion'] = Publicacion.objects.get(slug=self.kwargs['slug'])
        context['publicacion'].visitas +=1
        context['publicacion'].save(update_fields=['visitas'])
        context['galeria'] = Foto.objects.fotos_publicacion(self.kwargs['slug'])
        # context["favoritos"] = Favorito.objects.filter(user__id = self.request.user.id).values_list('producto__id',flat=True)
        context['comentarios'] = Comentario.objects.comentarios_publicacion(self.kwargs['slug']).order_by('-updated_at')[:10]
        
        x = list(Producto.objects.all().order_by('created_at')[:10])
        xx= random.sample(x,k=3)
        context['productos']= xx
        #USANDO EL PAGINATOR PARA CREAR UNA PAGINACION DE LOS COMENTARIOS QUE TIENE LA PUBLICACION
        # p = Paginator(x,5) 
        # page_number = self.request.GET.get('page')
        # page_obj = p.get_page(page_number)
        # context['comentarios'] = page_obj
        
        #context['edad_prom'] = Comentario.objects.comentarios_publicacion(self.kwargs['slug']).aggregate(prom=Avg('user__perfil__edad',distinct=True))
        
        return context
    
    def form_valid(self,form):

        form.instance.user = self.request.user
        form.instance.Publicacion = Publicacion.objects.get(slug=self.kwargs['slug'])

        return super(PublicacionView,self).form_valid(form)
    
    def get_success_url(self):
        return self.request.path


class NewPostView(LoginRequiredMixin,CreateView):
    
    form_class = NewPostForm
    template_name = "publicaciones/crear.html"
    success_url = reverse_lazy('posts_app:publicaciones')
    login_url = reverse_lazy('home_app:loginusuario')
    # extra_context = {'foto_formset': BookFormSet}
    
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["foto_formset"] = PostFormSet
        return context
    
    
    def form_valid(self,form):

        form.instance.user = self.request.user
        
        t = form.save()
        pub = Publicacion.objects.get(pk=t.id)
        formset = PostFormSet(self.request.POST, self.request.FILES, instance=pub)
        print(formset)
        formset.save()

        return super(NewPostView,self).form_valid(form)
    


class PostUpdateView(LoginRequiredMixin,UpdateView):
    
    model = Publicacion
    form_class = NewPostForm
    template_name = "publicaciones/actualizar.html"
    login_url = reverse_lazy('home_app:loginusuario')
    
    def get_success_url(self):
        slug = self.kwargs['slug']
        return reverse_lazy('posts_app:detallepost', kwargs={'slug': slug})
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["foto_formset"] = PostFormSet
        context["fotos"] = Foto.objects.filter(publicacion__slug=self.kwargs['slug'])
        context["pub"] = Publicacion.objects.get(slug=self.kwargs['slug'])
        return context
    
    
    def form_valid(self,form):

        form.instance.user = self.request.user
        
        t = form.save()
        pub = Publicacion.objects.get(pk=t.id)
        formset = PostFormSet(self.request.POST, self.request.FILES, instance=pub)
        print(formset)
        formset.save()
        messages.success(self.request,"Publicación actualizada con exito")

        return super(PostUpdateView,self).form_valid(form)


class FotoDeleteView(LoginRequiredMixin,View):
    login_url = reverse_lazy('home_app:loginusuario')
    
    def post(self,request,*args,**kwargs):
        # print(self.kwargs["pk"])
        foto = Foto.objects.get(id=self.kwargs["pk"])
        foto.delete()
        messages.success(self.request, 'Foto borrada')        
        
        return HttpResponseRedirect(self.request.META.get('HTTP_REFERER'))

rotar/templates/publicaciones/actualizar.html
{% extends 'base.html' %}
{%load static%}

{% block title %}Editar publicación{% endblock title %}


{% block content %}
{% if messages %}
{% for message in messages %}

<div class="alert alert-info m-0 p-2 px-3 " role="alert">
    <div class="container">

        <div class="row d-flex justify-content-between">
            {{message}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    
        </div>
    </div>
</div>
{% endfor %}
{% endif %}


{% if user.username == pub.user.username %}
<br>
<div class="container col-md-8">
    <h1> Editar publicación</h1>
    {{ form.media }}
    <form method="post" enctype='multipart/form-data' id="form1"> {% csrf_token %}
        <div class="row">
            <div class="col-md-6">
                <label class="form-label"> Titulo </label>{{form.titulo}}
            </div>
            <div class="col-md-6">
                <label class="form-label"> Resumen </label>{{form.resumen}}
            </div>
        </div>
        <div class="row align-items-center">
            <div class="col-md-6">
                <label class="form-label"> Etiquetas </label>{{form.etiquetas}}
            </div>
            <div class="col-md-6">
                <label class="form-label"> Imagen </label>{{form.imagen}}
                <br>
                <label class="form-label fs-5 fw-bold"> Publicar? {{form.publico}} </label> 

            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <label class="form-label"> Descripción </label>{{form.descripcion}}
            </div>
        </div>
        <div class="row">
            <div class="fs-4 py-2">Galeria de fotos</div>
        </div>
        <div class="row">
            <div class="col-md-6">
                {% for foto in fotos %}
                <div class="row align-items-center">
                    <div class="col-md-3">
                        <a role="button" data-bs-toggle="modal" data-bs-target="#exampleModal{{foto.id}}"><img src="{{foto.imagen.url}}" alt="" class="w-100 rounded" ></a>
                    </div>
                    <div class="modal fade" id="exampleModal{{foto.id}}" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-lg">
                          <div class="modal-content">
                            <div class="modal-header">
                              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <img src="{{foto.imagen.url}}" alt="" class="w-100 rounded" >
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                            </div>
                          </div>
                        </div>
                      </div>
                    <div class="col-md-6">
                        {{foto.imagen.name}}
                    </div>    
                    <div class="col-md-3">
                        <form action="{% url 'posts_app:borrarfoto' foto.id  %}" method="post" id="form2"> {% csrf_token %}
                            <button type="submit" class="btn btn-danger" form="form2"> <i class="far fa-trash-alt" ></i> </button>
                        </form>
                    </div>

                </div>
                {% endfor %}

            </div>
            <div class="col-md-6 rounded ">
            <div class="row justify-content-center">
                    
                    {{ foto_formset.management_form }}
                    {% for form in  foto_formset %}
                    <div class='table'>
                    <table class='no_error'>
                        {{form.imagen}}
                    </table>
                    </div>
                    {% endfor %}
                   <input type="button" value="Agregar más" id="add_more" class="btn btn-outline-success">
                    
                </div>
            </div>
                
        </div>
        <br>
        
        <div class="row"><button type="submit" class="btn btn-outline-success" form="form1">Actualizar</button></div>
        
    </form>
</div>

    {% else %}

    <div class="container">

        <h1>Necesitas de más permisos para acceder a esta pagina</h1>

    </div>

{% endif %}
        


{% endblock content %}

rotar/templates/publicaciones/crear.html
{% extends 'base.html' %}
{%load static%}

{% block title %}Nueva publicación{% endblock title %}


{% block content %}
    


{% if user.is_staff %}
<br>
<div class="container col-md-8">
    <h1> Nueva publicación</h1>
    {{ form.media }}
    <form method="post" enctype='multipart/form-data'> {% csrf_token %}
        <div class="row">
            <div class="col-md-6">
                <label class="form-label"> Titulo </label>{{form.titulo}}
            </div>
            <div class="col-md-6">
                <label class="form-label"> Resumen </label>{{form.resumen}}
            </div>
        </div>
        <div class="row align-items-center">
            <div class="col-md-6">
                <label class="form-label"> Etiquetas </label>{{form.etiquetas}}
            </div>
            <div class="col-md-6">
                <label class="form-label"> Imagen </label>{{form.imagen}}
                <br>
                <label class="form-label fs-5 fw-bold"> Publicar? {{form.publico}} </label> 

            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <label class="form-label"> Descripción </label>{{form.descripcion}}
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-6 m-2 border border-danger rounded ">
                <div class="fs-4 py-2">Galeria de fotos</div>
                {{ foto_formset.management_form }}
                {% for form in  foto_formset %}
                <div class='table'>
                <table class='no_error'>
                    {{form.imagen}}
                </table>
                </div>
                {% endfor %}
               <input type="button" value="Add More" id="add_more" class="btn btn-outline-success">
                
            </div>
        </div>
        
        <div class="row"><button type="submit" class="btn btn-outline-success">Crear</button></div>
        
    </form>
</div>

    {% else %}

    <div class="container">

        <h1>Necesitas de más permisos para acceder a esta pagina</h1>

    </div>

    {% endif %}
        


{% endblock content %}

rotar/templates/publicaciones/detalle.html
{% extends 'base.html' %}
{%load static%}
{% load humanize %}
{% block title %}Publicación {{publicacion.titulo}}{% endblock title %}


{% block content %}

{% if messages %}
{% for message in messages %}

<div class="alert alert-info m-0 p-2 px-3 " role="alert">
    <div class="container">

        <div class="row d-flex justify-content-between">
            {{message}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    
        </div>
    </div>
</div>
{% endfor %}
{% endif %}
<br>
<div class="container">
    <div class="row">
        <div class="col-md-9 bg-light rounded">
            <br>
            <div class="row text-center py-2">
                <h1>{{publicacion.titulo}}</h1>
            </div>
            <br>
            <div class="row px-2">
                <div class="col-md-6">
                    <div class="fs-4">Resumen: {{publicacion.resumen}} </div>
                    <hr class="mt-1 mb-2 p-0 text-primary">
                    <div class="row">
                        <div class="col-md-4 pe-0">
                            
                            <div class="fs-5 text-secondary fst-italic">Publicado</div>
                            <div class="fs-5">Publicado por</div>
                            <div class="fs-5">Visitas</div>
                            <div class="fs-5">Fotos</div>
                            <div class="fs-5">Comentarios</div>
                            <div class="fs-5">Etiquetas</div>
                        </div>
                        <div class="col-md-8">
                            <div class="fs-5 text-secondary fst-italic"> {{publicacion.created_at}}</div>
                            <div class="fs-5"> {{publicacion.user.username}}</div>
                            <div class="fs-5"> {{publicacion.visitas}}</div>
                            <div class="fs-5"> {{galeria|length}}</div>
                            <div class="fs-5"> {{comentarios|length}}</div>
                            <div class="fs-5">
                                {% for et in publicacion.etiquetas.all %}
                                <span class="badge rounded-pill bg-primary fs-6">{{et.nombre}}</span>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        
                        {% if user.username == publicacion.user.username %}
                            <a href="{% url 'posts_app:editpost' publicacion.slug %}" class="text-decoration-none fs-4">Editar publicación </a>
                        {% endif %}
                            
                    </div>
                </div>
                <div class="col-md-6">
                    {% if publicacion.video %}
                    <div class="container">
                        <div class="row">
                            <div class="col-md-6">
        
                                <video controls autoplay class="d-block w-100 rounded">
                                    <source src="{{publicacion.video.url}}" type="video/mp4">
                                    Your browser does not support the video tag.
                                </video>
                            </div>
                        </div>
                    </div>
                    {% else %}
                    <a role="button" data-bs-toggle="modal" data-bs-target="#exampleModal{{publicacion.id}}"><img src="{{publicacion.imagen.url}}" alt="" class="w-100 rounded" ></a>
                    <div class="modal fade" id="exampleModal{{publicacion.id}}" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-lg">
                          <div class="modal-content">
                            <div class="modal-header">
                              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <img src="{{publicacion.imagen.url}}" alt="" class="w-100 rounded" >
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                            </div>
                          </div>
                        </div>
                      </div>
                    {% endif %}
                </div>
            </div>
            <br>
            <div class="row px-2">
                <div class="fs-5">
                    {{publicacion.descripcion|safe}}
                </div>
        
            </div>
            <br>
        
            <div class="row">
        
                <div class="col-md-6">
                    <div class="fs-1 fw-light text-center">Galeria de fotos</div>
                    <br>
                    {% if galeria %}
        
                    <div id="carouselExampleFade" class="carousel slide carousel-fade" data-bs-ride="carousel">
                        <div class="carousel-inner">
                            {% for foto in galeria %}
        
                            {% if forloop.first %}
                            <div class="carousel-item active">
                                <img src="{{foto.imagen.url}}" class="d-block w-100 rounded" alt="..." style="height: 400px;">
                            </div>
        
                            {% else %}
                            <div class="carousel-item">
                                <img src="{{foto.imagen.url}}" class="d-block w-100 rounded" alt="..." style="height: 400px;">
                            </div>
        
                            {% endif %}
        
                            {% endfor %}
                        </div>
                        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade"
                            data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Previous</span>
                        </button>
                        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade"
                            data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Next</span>
                        </button>
                    </div>
                    {% endif %}
                </div>
                <div class="col-md-6">
                    <div class="fs-1 fw-light text-center">Comentarios</div>
                    <br>
                    <div class="row d-flex justify-content-center">
                        <div class="container px-0 overflow-auto" style="max-height: 400px;">
                            {% for comen in comentarios %}
                            <div class="row border border-primary rounded align-items-center p-1 m-1">
                                <div class="col-md-2 justify-content-center">
                                    {% if comen.user.perfil.foto %}
                                    <img src="{{comen.user.perfil.foto.url}}" class="d-block w-100 rounded">
        
                                    {% else %}
                                    <img src="{% static 'img/no-image.png' %}" class="d-block w-100 rounded">
                                    {% endif %}
                                    <small class="text-success text-start">{{comen.user.username}}</small>
                                    
                                </div>
                                <div class="col-md-2 text-secondary pe-1 lh-1">
                                    <small style="font-size: 0.8rem;"> {{comen.created_at|timesince}} </small>
                                </div>
                                
                                <div class="col-md-8">
                                    <div class="fs-6 fw-light" >{{comen.mensaje}}</div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    {% if user.username %}
                    <br>
                    <div class="row">
                        <form method="post" enctype='multipart/form-data'> {% csrf_token %}
                            <div class="row">
        
                                <div class="col-md-9 p-1">
                
                                        <textarea name="mensaje" id="id_mensaje" class="form-control" placeholder="Deje su comentario aqui..." rows="2"></textarea>
                                </div>
                                <div class="col-md-3 d-flex">
                                        
                                    <button type="submit" class="btn btn-outline-success flex-fill">Comentar</button>
                                </div>
                            </div>
                            
                        </form>
                    </div>
                    {% endif %}
                <br>
                </div>
            </div>
        
        </div>
                
        <div class="container col-md-3">
            <div class="row bg-dark rounded align-items-center mb-2 mx-1">
                <div class="col-md-3">
                    <div class="fs-2">
                        <img src="{% static 'img/logoblanco.png' %}" alt="" class="w-100 d-block">
                    </div>
                </div>
                <div class="col-md-9 p-0">
                    <div class="fs-2 text-center bg-dark rounded text-white my-1 lh-sm">Productos recomendados</div>
                </div>
            </div>
            <div class="row mx-1">
                
                {% for p in productos  %}
                    {% include 'cajaproducto.html' %}

                {% endfor %}
            </div>
        </div>

    </div>
</div>

<br>




{% endblock content %}