Apps/home/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "home_app"

urlpatterns = [
    path('',views.Inicio.as_view(),name="inicio"),
    path('registro',views.UserCreateView.as_view(),name="registrousuario"),
    path('login',views.Login.as_view(),name="loginusuario"),
    path('logout',views.Logout.as_view(),name="logoutusuario"),
    path('cambiarpassword',views.CambiarPassword.as_view(),name="cambiarpassword"),
    path('detalleusuario/<slug>/',views.UserDetailView.as_view(),name="detalleusuario"),
    path('updateusuario/',views.UsuarioUpdateView.as_view(),name="updateusuario"),
    path('eliminarusuario',views.UserDeleteView.as_view(),name="eliminarcuenta"),
    path('shoppingrecord',views.UserShoppingRecordView.as_view(),name="historialcompras"),
]

Apps/producto/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "productos_app"

urlpatterns = [
   path('productos',views.VistaProductos.as_view(),name="productos"),
   path('detalleproducto/<slug>/',views.DetalleProducto.as_view(),name="detalle"),
   path('agregarfavorito/<producto>/',views.FavoritoCreateView.as_view(),name="addfavorito"),
   path('carrito',views.VistaCarrito.as_view(),name="carrito"),
   path('borrardelcarrito/<producto>',views.BorrarDelCarrito.as_view(),name="borrardelcarrito"),
]

Apps/publicaciones/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "posts_app"

urlpatterns = [
    path('publicaciones',views.VistaPublicaciones.as_view(),name="publicaciones"),
    path('publicacion/<slug>',views.PublicacionView.as_view(),name="detallepost"),
    path('nuevapublicacion',views.NewPostView.as_view(),name="newpost"),
    path('editarpublicacion/<slug>',views.PostUpdateView.as_view(),name="editpost"),
    path('borrarfoto/<pk>',views.FotoDeleteView.as_view(),name="borrarfoto"),
]

rotar/urls.py
from django.contrib import admin
from django.urls import path, re_path,include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap

from Apps.home.sitemap import ProductosSitemap, Sitemap


sitemaps = {
    'site': Sitemap(['home_app:inicio']),
    'productos': ProductosSitemap
}

urlpatterns_sitemap = [
    path('sitemap.xml', sitemap,{'sitemaps':sitemaps},
    name='django.contrib.sitemaps.views,sitemap')

]

urlpatterns_main = [
    path('admin/', admin.site.urls),
    re_path('',include('Apps.home.urls')),
    re_path('',include('Apps.publicaciones.urls')),
    re_path('',include('Apps.producto.urls')),

    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns_main + urlpatterns_sitemap

Apps/home/models.py
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.conf import settings

from ckeditor.fields import RichTextField

from django.contrib.auth.models import AbstractUser
from django.template.defaultfilters import slugify

class User(AbstractUser):
    slug = models.SlugField()
    
    def save(self,*args, **kwargs):
        
        slug_unique = '%s' % (self.username)
        self.slug = slugify(slug_unique)

        super(User,self).save(*args, **kwargs)
        

# Create your models here.

class Departamento(models.Model):
    nombre = models.CharField(verbose_name="Nombre", max_length=100)
    abreviacion = models.CharField(verbose_name="Abreviación", max_length=50)

    class Meta:
        verbose_name = "Departamento"
        verbose_name_plural = "Departamentos"
    
    def __str__(self):
        return self.nombre

class Perfil(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, verbose_name=("Usuario"), on_delete=models.CASCADE)
    cargo= models.CharField(verbose_name="Cargo", max_length=150,blank=True)
    bio = RichTextField(verbose_name="Biografía",blank=True)
    edad = models.IntegerField(default=0)
    departamento = models.ForeignKey(Departamento, verbose_name=("Departamento"), on_delete=models.CASCADE,blank=True, null=True)
    foto = models.ImageField(upload_to="media", height_field=None, width_field=None, max_length=None, blank=True)
    linkedin = models.URLField(verbose_name=("Perfil linkedin"), max_length=200, blank=True)
    
    class Meta:
        verbose_name = "Perfil"
        verbose_name_plural = "Perfiles"
    
    def __str__(self):
        return self.user.get_full_name()
    

        
    
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Perfil.objects.create(user=instance)
        

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.perfil.save()

class Servicio(models.Model):
    nombre = models.CharField(max_length=150)
    resumen = models.CharField(max_length=250, default=" ")
    descripcion = RichTextField(verbose_name="Descripción")
    imagen = models.ImageField(upload_to="media", height_field=None, width_field=None, max_length=None)
    
    class Meta:
        verbose_name = "Servicio"
        verbose_name_plural = "Servicios"
    
    def __str__(self):
        return self.nombre

Apps/home/forms.py
from django import forms

from .models import Perfil
from django.contrib.auth import get_user_model
User = get_user_model()

from django.contrib.auth.forms import UserCreationForm
from ckeditor.fields import RichTextFormField, CKEditorWidget


#Formularios para actualizar perfil y usuario al tiempo
class UserForm(forms.ModelForm):
    
    class Meta:
        model = User
        fields= ('first_name','last_name','email',)
        widgets= {
            'first_name': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'last_name': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'email': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
        }
        

class ProfileForm(forms.ModelForm):
    
    bio = RichTextFormField(config_name="refault")
    
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs) 
        self.fields['departamento'].empty_label = None
    
    class Meta:    
        
        model = Perfil
        fields= ('cargo','bio','departamento','foto','linkedin')
        
        widgets= {
            'cargo': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'departamento': forms.Select(
                attrs={
                    'class': 'form-select'
                }
            ),
            'foto': forms.FileInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'linkedin': forms.URLInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'https://www.linkedin.com/in/usuario123/'
                }
            )
            
        }
    

#Crear usuario
class UserCreateForm(UserCreationForm):
    
    def __init__(self, *args, **kwargs):
        super(UserCreateForm, self).__init__(*args, **kwargs)

        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'
    
    username = forms.CharField(
            label='Username',
            required=True,
            widget=forms.TextInput(
                attrs={
                    'class': "form-control",
                }
            )
        )
    email = forms.EmailField(
            label='Email',
            required=True,
            widget=forms.EmailInput(
                attrs={
                    'class': "form-control",
                }
            )
        )
    class Meta:
        model = User
        fields = ("username","email")
    
    
    # def save(self, commit=True):
    #     user = super().save(commit=False)
         
    #     user.set_password(self.cleaned_data["password1"])
    #     user.is_active = False
    #     if commit:
    #         user.save()
    #     return user

Apps/home/views.py
from django.shortcuts import redirect, render

from django.views.generic import CreateView, TemplateView, DetailView, UpdateView, FormView, View
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin 
from django.contrib.messages.views import SuccessMessageMixin 

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.http import HttpResponse
from django.http.response import HttpResponseRedirect
from django.urls.base import reverse
from django.db.models import Count
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView

from Apps.publicaciones.models import Comentario, Etiqueta, Publicacion
from Apps.home.models import Perfil, Servicio
from Apps.home.forms import ProfileForm, UserForm, UserCreateForm
from django.contrib.auth import logout

import random
import string
from Apps.producto.models import DetalleVenta, Favorito, Producto

from django.contrib.auth import get_user_model
from django.core.paginator import Paginator
User = get_user_model()

# def code_generator(size=6,chars=string.ascii_uppercase + string.digits):
#     return ''.join(random.choice(chars) for _ in range(size))



#from Apps.home.forms import UserRegisterForm
# Create your views here.
class Inicio(TemplateView):
    template_name = "home/inicio.html"
    
    
    def get_context_data(self, **kwargs):
        context = super(Inicio, self).get_context_data(**kwargs)
        
        #muestra de productos
        muestra_productos= list(Producto.objects.all().order_by('-created_at')[:10])
        productos_nuevos = random.sample(muestra_productos,k=4)
        context["productos"] = productos_nuevos
        
        #muestra de populares
        muestra_populares = list(Producto.objects.all().order_by('-visitas')[:10])
        populares = random.sample(muestra_populares,k=3)
        context["populares"] = populares
        
        #muestra de publicaciones
        muestra_publicaciones = list(Publicacion.objects.all().order_by('-created_at')[:3])
        publicaciones_nuevas = random.sample(muestra_publicaciones,k=2)
        context["publicaciones"] = publicaciones_nuevas
        
        #primeros servicios
        
        context["servicios"] = Servicio.objects.all().order_by('id')[:3]
        
        return context
    


class UserCreateView(SuccessMessageMixin,CreateView):
    form_class = UserCreateForm
    template_name = "home/registro.html"
    success_url = reverse_lazy('home_app:loginusuario')
    success_message = "Usuario registrado con exito, por favor inicie sesión..."
    

class Login(SuccessMessageMixin,LoginView):
    template_name = 'home/login.html'
    success_message = "Bienvenido!!!"
    
class Logout(LoginRequiredMixin,LogoutView):
    login_url = reverse_lazy('home_app:loginusuario')
    next_page = reverse_lazy('home_app:inicio')
    
    def get_next_page(self):
        next_page = super(Logout, self).get_next_page()
        messages.success(self.request, 'Hasta Pronto')
        return next_page
    
class CambiarPassword(LoginRequiredMixin,PasswordChangeView):
    template_name = "home/cambiarpassword.html"
    success_url = reverse_lazy('home_app:loginusuario')
    login_url = reverse_lazy('home_app:loginusuario')
    
    def form_valid(self, form):
        messages.success(self.request, "Contraseña modificada correctamente, por favor inicie sesión nuevamente")
        logout(self.request)
        return super().form_valid(form)

class UserDetailView(DetailView):
    
    template_name = "home/detalleusuario.html"
    model = User
    context_object_name = 'usuario'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.kwargs['slug']
        context["etiquetas"] = Etiqueta.objects.etiquetas_usuarios(user)
        
        #TODO: Paginacion del historial de comentarios del usuario
        
        context["comentarios"] = Comentario.objects.filter(user__slug=user).order_by('-created_at')[:10]
        context["total_comentarios"] = Comentario.objects.filter(user__slug=user).aggregate(total=Count('id'))
        x = Favorito.objects.filter(user__slug=user).order_by('-created_at')
        
        #USANDO EL PAGINATOR PARA CREAR UNA PAGINACION DE LOS COMENTARIOS QUE TIENE LA PUBLICACION
        p = Paginator(x,6) 
        page_number = self.request.GET.get('page')
        page_obj = p.get_page(page_number)
        context["page_obj"] = page_obj
        
        return context
    
    

#Una forma de hacer sin clases dos formularios


# @login_required
# def update_profile(request):
    
#     if request.method == 'POST':
#         user_form = UserForm(request.POST, instance=request.user)
#         profile_form = ProfileForm(request.POST, instance=request.user.perfil)
#         if user_form.is_valid() and profile_form.is_valid():
#             user_form.save()
#             profile_form.save()
#             messages.success(request, ('Your profile was successfully updated!'))
#             return redirect(reverse_lazy('home_app:detalleusuario')) #falta arreglar esto
#         else:
#             messages.error(request, ('Please correct the error below.'))
#     else:
#         user_form = UserForm(instance=request.user)
#         profile_form = ProfileForm(instance=request.user.perfil)
        
#     return render(request, 'home/update.html', {
#         'form': user_form,
#         'profile_form': profile_form
#     })
    
class UsuarioUpdateView(LoginRequiredMixin,FormView):
    
    form_class = UserForm
    template_name = "home/update.html"
    success_url = reverse_lazy('home_app:inicio')
    extra_context = {'profile_form': ProfileForm}
    login_url = reverse_lazy('home_app:loginusuario')
    
    def get_context_data(self, **kwargs):
        context = super(UsuarioUpdateView,self).get_context_data(**kwargs)
        
        context['form'] = UserForm(instance=self.request.user) 
        context['profile_form'] = ProfileForm(instance=self.request.user.perfil)
        
        return context
    
    def form_valid(self, form):

        user_form = UserForm(self.request.POST,  instance=self.request.user)
        profile_form = ProfileForm(self.request.POST,self.request.FILES, instance=self.request.user.perfil)
        user_form.save()
        profile_form.save()
        
        return super().form_valid(form)

class UserDeleteView(LoginRequiredMixin,View):
    login_url = reverse_lazy('home_app:loginusuario')
    
    def post(self,request,*args,**kwargs):
        
        user = User.objects.get(id=self.request.user.id)
        user.delete()
        messages.success(self.request, 'Cuenta eliminada con exito')        
        
        return HttpResponseRedirect(
                reverse(
                    'home_app:inicio'
                )
            )


class UserShoppingRecordView(LoginRequiredMixin,TemplateView):
    template_name = "home/shoppingrecord.html"
    login_url = reverse_lazy('home_app:loginusuario')
    
    def get_context_data(self, **kwargs):
        context = super(UserShoppingRecordView, self).get_context_data(**kwargs)
        
        context['record'] = DetalleVenta.objects.filter(venta__user__id=self.request.user.id).order_by('-venta__fecha_venta')
        
        return context
        

rotar/templates/home/detalleusuario.html
{% extends 'base.html' %}
{%load static%}
{% load humanize %}
{% block title %}Perfil usuario {{usuario.username}}{% endblock title %}


{% block content %}
<br>
<div class="container col-md-8 bg-light rounded">
    <br>
    <div class="row mb-3">
        <div class="col-md-7">
            <div class="fs-1">  <i class="fas fa-user-astronaut"> </i> Perfil de usuario</div>
        </div>
        <div class="col-md-5">
            {% if user.id == usuario.id %}
            <div class="row flex-row-reverse">
                <div class="col-md-12 d-flex justify-content-end">

                    <a class="btn btn-dark mx-2" href="{% url 'home_app:updateusuario' %}"> Editar Perfil</a>
                    <a class="btn btn-dark" href="{% url 'home_app:cambiarpassword' %}"> Cambiar contraseña</a>

                </div>
            </div>
            {% endif %}
        </div>
    </div>

    <div container>
        <div class="row">
            <div class="col-md-7">
                <div class="fs-2 m-0 p-0">Nombre: {{usuario.first_name}} {{usuario.last_name}} </div>
                <hr class="mt-1 mb-2 p-0 text-primary">
                <div class="row">
                    <div class="col-md-3 pe-0">
                        <div class="fs-5">Username</div>
                        <div class="fs-5">Email</div>
                        <div class="fs-5 text-secondary fst-italic">Usuario desde</div>
                        {% if usuario.perfil.departamento %}
                        <div class="fs-5">Departamento</div>
                        {% endif %}
                        {% if usuario.perfil.cargo%}
                        <div class="fs-5">Cargo</div>
                        {% endif %}
                        <div class="fs-5"><i class="fab fa-linkedin"></i> Linkedin</div>
                    </div>
                    <div class="col-md-9">
                        <div class="fs-5"> {{usuario.username}}</div>
                        <div class="fs-5"> {{usuario.email}}</div>
                        <div class="fs-5 text-secondary fst-italic"> {{usuario.date_joined|date:"d F Y"}}</div>
                        {% if usuario.perfil.departamento %}
                        <div class="fs-5">{{usuario.perfil.departamento}}</div>
                        {% endif %}
                        {% if usuario.perfil.cargo%}
                        <div class="fs-5">{{usuario.perfil.cargo}}</div>
                        {% endif %}
                        
                        {% if usuario.perfil.linkedin %}
                            
                        <div class="fs-5"><a href="{{usuario.perfil.linkedin}}">{{usuario.perfil.linkedin}}</a></div>
                        {% endif %}
                            

                    </div>
                </div>
                <br>
                <div class="row">
                    <h5>Resumen:</h5>
                    <div class="fs-5 fw-light lh-sm">{{usuario.perfil.bio|safe|truncatechars:200}}</div>
                </div>
                <br>
            </div>

            <div class="col-md-5">

                {% if usuario.perfil.foto %}

                <a role="button" data-bs-toggle="modal" data-bs-target="#exampleModal"><img src="{{usuario.perfil.foto.url}}" alt="" class="w-100 rounded resaltar" ></a>

                <div class="modal fade" id="exampleModal" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-lg">
                      <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <img src="{{usuario.perfil.foto.url}}" alt="" class="w-100 rounded" >
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                        </div>
                      </div>
                    </div>
                  </div>
                {% else %}
                <img class="w-100 rounded" src="{% static 'img/no-image.png' %}" alt="">
                
                {% endif %}
                {% if user.username == usuario.username %}
                <a href="{% url 'home_app:historialcompras' %}" class="text-decoration-none fs-5 fw-light">Ver historial de compras</a>                    
                {% endif %}
                    
            </div>

        </div>

    </div>

    {% if user.username == usuario.username %}
    <div class="row pe-2">
        
        <div class="col-md-6"><h1>Productos favoritos:</h1></div>
        <div class="col-md-6 align-self-center text-end">
            <div class="fs-5 text-primary">Total: {{page_obj.paginator.count}} </div>
        </div>
    </div>
    {% if page_obj %}
            
        <div class="container">
            <div class="row">
                {% for fav in page_obj %}

            <div class="col-md-4 p-2">
                <div class="col-12 border border-info rounded p-1 resaltar">

                    <div class="row align-self-center text-center" style="min-height: 60px;">
                        <a href="{% url 'productos_app:detalle' fav.producto.slug %}" class="text-decoration-none align-self-center fs-5 text-center text-dark">{{fav.producto.nombre|truncatechars:60}}</a>
                
                    </div>
                    <div class="row d-flex align-items-center">
                        <div class="d-flex justify-content-center">

                            <a href="{% url 'productos_app:detalle' fav.producto.slug %}"><img src="{{fav.producto.imagen.url}}" class="d-block rounded mw-100" style="height: 200px;" /></a>
                        </div>
                    </div>

                    <div class="col-md-10 text-secondary"><small> Publicado el {{fav.producto.created_at|date:"D d M Y"}}</small>

                    </div>

                    <div class="col-12">
                        <div class="row">


                            <div class="col-8">
                                Precio: <strong class="text-danger"> $ {{fav.producto.precio|intcomma}}</strong>

                            </div>
                            <div class="col-4 text-end">
                                <i class="far fa-eye"></i> {{fav.producto.visitas}} &nbsp;

                            </div>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="row">
                            <div class="col-md-8">
                                Marca: {{fav.producto.marca}} <br>
                                <span> Categoria: {{fav.producto.categoria.nombre}}</span>
                            </div>
                            <div class="col-md-4 text-end">

                                <form action="{% url 'productos_app:addfavorito' fav.producto.id %}" method="post"> {% csrf_token %}

                                    <p><button type="submit" class="btn">
                                            <i class="fas fa-star"></i>
                                        </button> </p>

                                </form>
                            </div>

                        </div>
                    </div>

                </div>
            </div>

            {% endfor %}
                
            </div>
            <div class="row">
                
            {% include 'paginacion.html' %}
                    
            </div>
            <hr>
        </div>

        {% else %}

        <h3 class="text-warning">Aun no tienes productos en tu lista de favoritos</h3>
        <hr>
        {% endif %}
    
    <div class="row pe-2">
    
        <div class="col-md-6"><h1>Ultimos comentarios:</h1></div>
        <div class="col-md-6 align-self-center text-end">
            <div class="fs-5 text-primary">Total: {{total_comentarios.total}} </div>
        </div>
    </div>
    
    {% if comentarios %}
    
    {% else %}

    {% endif %}
        
        
    <div class="row text-center text-primary fs-5">
        <div class="col-md-1">Item</div>
        <div class="col-md-2">Fecha publicado</div>
        <div class="col-md-3">Publicación</div>
        <div class="col-md-6">Mensaje</div>
    </div>
    <hr class="text-primary mb-1">
    {% for c in comentarios %}
     <div class="row align-items-center">
        <div class="col-md-1 text-center">{{forloop.counter}}</div>
        <div class="col-md-2">{{c.created_at}}</div>
        <div class="col-md-3 ">{{c.Publicacion.titulo}}</div>
        <div class="col-md-6">{{c.mensaje}}</div>
        </div>   
    
    {% if forloop.last %}
        
    {% else %}
    <hr class="text-primary m-1">

    {% endif %}
        
    {% endfor %}


    {% endif %}

</div>
<br>




{% endblock content %}

rotar/templates/home/inicio.html
{% extends 'base.html' %}
{%load static%}

{% block title %}Pagina inicio {% endblock title %}


{% block content %}
{% if messages %}
{% for message in messages %}

<div class="alert alert-info m-0 p-2 px-3 " role="alert">
    <div class="container">

        <div class="row d-flex justify-content-between">
            {{message}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    
        </div>
    </div>
</div>
{% endfor %}
{% endif %}
<img src="{% static 'img/fotoportada1.png' %}" alt="" class="img-fluid" style="min-height: 150px;">
<div class="container">
    <br>
    <div class="row justify-content-center">
        <div class="row mb-3">
            <h1> <i class="fas fa-meteor"></i> Ultimos productos</h1>
        </div>
        <br>
        <div class="row">

            {% for p in productos %}
            <div class="col-12 col-md-3 p-1">
                {% include 'cajaproducto.html' %}
            </div>

            {% endfor %}

        </div>
    </div>
    <br>
    <br>
</div>
<img src="{% static 'img/fotoportada3.png' %}" alt="" class="img-fluid" style="min-height: 200px;">
<div class="container">
    <br>
    <br>
    <div class="row">
        <h1> <i class="fas fa-meteor"></i> Ultimas publicaciones</h1>
    </div>
    <br>
    <div class="row">

        {% for p in publicaciones %}
        <div class="col-12 col-md-6 mb-2">
            <div class="row px-2">
                <div class="col-md-7 m-0 p-0">
                    <a href="{% url 'posts_app:detallepost' p.slug %}" class="text-decoration-none"><img src="{{p.imagen.url}}" class="w-100 rounded" style="min-height: 300px;"></a>
                </div>
                <div class="col-md-5">

                    <a class="text-decoration-none text-dark fs-4 fw-bold" href="{% url 'posts_app:detallepost' p.slug %}"> {{p.titulo|truncatechars:50}}</a>
                    <div class="fs-6 text-secondary fst-italic">{{p.created_at}}</div>
                    <br class="d-none d-sm-block">
                    <div class="fs-6"> {{p.resumen|truncatechars:80}}</div>


                </div>
            </div>
        </div>

        {% endfor %}

    </div>
    <br>
    <br>
    <div class="container">
        <br>
        <div class="row text-center">
            <h1> <i class="fas fa-meteor"></i> Explora con nosotros</h1>
            <div class="fs-5 text-secondry"> Soluciones para evolucionar en tu negocio </div>
        </div>
        <br>
        <br>
        <div class="row">
            {% for s in servicios %}

            <div class="col-md-4">
                <div class="card">
                    <img src="{{s.imagen.url}}" alt="" class="w-100 rounded" style="min-height: 250px;">
                    <div class="card-body" style="min-height: 150px;">
                        <h5 class="card-title">
                            {{s.nombre}}
                        </h5>
                        <p class="card-text">
                            {{s.resumen}}
                        </p>

                    </div>
                </div>

            </div>

            {% endfor %}

        </div>

    </div>
    <br>
    <div class="container">
        <br>
        <div class="row mb-3">
            <h1> <i class="fas fa-meteor"></i> Productos populares</h1>
        </div>
        <div class="row">
            {% for p in populares %}
            <div class="col-md-4 p-1">
                {% include 'cajaprodhtal.html' %}
            </div>
            {% endfor %}
        </div>
    </div>


</div>




{% endblock content %}

rotar/templates/home/update.html
{% extends 'base.html' %}
{%load static%}

{% block title %}Actualizar el perfil{% endblock title %}


{% block content %}
<br>
<div class="container col-md-7 border border-info rounded">
    <div class="row p-1 pt-3">
        <div class="col-md-9">
            <div class="fs-3"> Edición de Usuarios</div>
        </div>
        <div class="col-md-3">
            <div class="row pe-2">
                <button type="button" class="btn btn-danger text-white" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    Borrar mi cuenta
                  </button>
            </div>
            
              
              <!-- Modal -->
              <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">Estas seguro que deseas eliminar tu cuenta?</h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      Una vez elimines tu cuenta no podras recuperar los cambios...
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>

                      <form action="{% url 'home_app:eliminarcuenta' %}" method="post"> {% csrf_token %}
                        <button type="submit" class="btn btn-danger"> Borrar cuenta </button>
                    </form>
                    </div>
                  </div>
                </div>
              </div>
            
        </div>
        
    </div>
    <div class="row p-1 mb-3">
        {{ profile_form.media }}
        <form method="POST" enctype="multipart/form-data"> {% csrf_token %}
            
            <div class="form-group row g-1">
                <div class="col-md-6">
                    <label class="form-label">Nombre</label>{{form.first_name}}

                </div>
                <div class="col-md-6">

                    <label class="form-label">Apellido</label>{{form.last_name}}
                </div>
                <div class="col-md-6">
                    <label class="form-label">Email</label>{{form.email}}
                </div>
                <div class="col-md-6">
                    <label class="form-label">Foto</label>{{profile_form.foto}}
                </div>
                {% if user.is_staff %}
                <div class="col-md-6"><label class="form-label">Cargo</label>{{profile_form.cargo}}</div>
                <div class="col-md-6"><label class="form-label">Departamento</label>{{profile_form.departamento}}</div>
                <div class="col-md-12"><label class="form-label">Linkedin</label>{{profile_form.linkedin}}</div>
                  
                {% endif %}

                <div class="col-md-12">
                    <label class="form-label">Breve biografía</label>
                    {{profile_form.bio}}
                </div>
                <button type="submit" class="btn btn-outline-primary" >Actualizar</button>
            </div>
        
        </form>

    </div>
    
</div>


{% endblock content %}